config/routes.rb
Rails.application.routes.draw do

  root 'hospital#index'

  resources :clinics
  resources :patients do

    member do

      patch :wait_patient
      patch :checkup_patient
      patch :xray_patient
      patch :surgery_patient
      patch :bills_patient
      patch :leave_patient
    end
  end  
  resources :medications
  resources :doctors

end

app/models/clinic.rb
class Clinic < ActiveRecord::Base


has_many :patients, through: :clinic_patients	
has_many :clinic_patients
has_many :medications
has_many :doctors, through: :clinic_doctors
has_many :clinic_doctors

end

app/controllers/clinics_controller.rb
class ClinicsController < ApplicationController

	def index
		# @clinics = Clinic.search(params[:search])
		@clinics = Clinic.all
		@clinics = if !params[:q].blank?
      Clinic.where("name LIKE ?", "%#{params[:q]}%")
    else
      
      puts "Showing all Clinics"
      Clinic.all
    end.shuffle
	end

	def new
		@clinic = Clinic.new
		@doctors = Doctor.all
		@patients = @clinic.patients
	end

	def create
		@clinic = Clinic.create clinic_params
		redirect_to clinics_path
	end

	def show
		# @patients = @clinic.patients
		# @clinic = Clinic.find params[:id]
		@doctors = @clinic.doctors
		@patients = @clinic.patients
	end

	def edit
		@clinic = Clinic.find params[:id]
		@doctors = Doctor.all
		@patients = @clinic.patients
	end
		
	def update
		@clinic = Clinic.find params[:id]
		@clinic.update_attributes clinic_params
		redirect_to clinics_path
	end	

	def destroy
		@clinic = Clinic.find params[:id]
		@clinic.delete
		redirect_to clinics_path
	end

private
	def clinic_params
		params.require(:clinic).permit(
			:name,
			:facility_type,
			:address,
			:city,
			:state,
			patient_ids: [],
			clinic_ids: [],
			doctor_ids: []
			)
	end
end

app/helpers/clinics_helper.rb
module ClinicsHelper
end

app/views/clinics/_form.html.haml
= form_for @clinic do |f|
  = f.label :name
  = f.text_field :name
  %br/
  = f.label :facility_type
  = f.text_field :facility_type
  %br/
  = f.label :address
  = f.text_field :address
  %br/
  = f.label :city
  = f.text_field :city
  %br/
  = f.label :state
  = f.text_field :state
  %br/
  - @doctors.each do |d|
    = check_box_tag 'clinic[doctor_ids][]', d.id, @clinic.doctors.include?(d)
    = d.name
  %br/
  %br/
  = f.submit

app/views/clinics/edit.html.haml
= render 'form'

app/views/clinics/index.html.haml
%h1 Clinics
= form_tag clinics_path, method: :get, role: "search" do
  = text_field_tag 'q', params[:q], id: "srch-term", placeholder: "Search" 
  = submit_tag "Search"

- @clinics.each do |clinic|
  = link_to clinic.name, clinic_path(clinic)
  %br/
  %br/
 
= link_to "Home", root_path
= link_to "Add Clinic", new_clinic_path

app/views/clinics/new.html.haml
%h1 Add Clinics
= render 'form'
= link_to "Home", root_path
= link_to "Clinics", clinics_path

app/views/clinics/show.html.haml
= @clinic.name
%br/
= @clinic.facility_type
%br/
= @clinic.address
%br/
= @clinic.city
%br/
= @clinic.state
%br/
= link_to "Edit", edit_clinic_path(@clinic)
= link_to "Delete", clinic_path(@clinic), method: :delete
%br/
%br/
%div Affiliated Doctors
- @doctors.each do |doctor|
  = doctor.name
  %br/
%br/
%br/
= link_to "Home", root_path
= link_to "Clinics", clinics_path