config/routes.rb
Rails.application.routes.draw do

  root 'hospital#index'

  resources :clinics
  resources :patients do

    member do

      patch :wait_patient
      patch :checkup_patient
      patch :xray_patient
      patch :surgery_patient
      patch :bills_patient
      patch :leave_patient
    end
  end  
  resources :medications
  resources :doctors

end

app/models/medication.rb
class Medication < ActiveRecord::Base
validates :name, presence: true
	# belongs_to :patient

	has_many :patient_medications
  has_many :patients, through: :patient_medications
end

app/controllers/medications_controller.rb
class MedicationsController < ApplicationController

def index
	@medications = Medication.all
	@medications = if !params[:q].blank?
    Medication.where("name LIKE ?", "%#{params[:q]}%")
  else
    
    puts "Showing all Medications"
    Medication.all
  end.shuffle
end

def new
	@medication = Medication.new
end	

def edit
	@medication = Medication.find params[:id]
end	

def show
	@medication = Medication.find params[:id]
end

def create
	@medication = Medication.create medication_params
	redirect_to medications_path
end

def update
	@medication = Medication.find params[:id]
	@medication.update_attributes medication_params
	redirect_to medications_path
end

def destroy
	@medication = Medication.find params[:id]
	@medication.delete
	redirect_to medications_path
end

private
	def medication_params
		params.require(:medication).permit(
			:name,
			:dosage,
			:directions,
			:prescriber,
			patient_ids: []
			)
	end
end

app/helpers/medications_helper.rb
module MedicationsHelper
end

app/views/medications/_form.html.haml
= form_for @medication do |f|
  = f.label :name
  = f.text_field :name, class: "form-control"
  %br/
  = f.label :dosage
  = f.text_field :dosage
  %br/
  = f.label :directions
  = f.text_field :directions
  %br/
  = f.label :prescriber
  = f.text_field :prescriber
  %br/
  %br/
  = f.submit "Submit", class: "button", disabled: "disabled"

app/views/medications/edit.html.haml
%h1 edit
= render 'form'

app/views/medications/index.html.haml
%h1 Meds
%br
= form_tag medications_path, method: :get, role: "search" do
  = text_field_tag 'q', params[:q], id: "srch-term", placeholder: "Search" 
  = submit_tag "Search"
%br
- @medications.each do |f|
  = f.name
  %br/
  = f.dosage
  %br/
  = f.directions
  %br/
  = f.prescriber
  %br/
  = link_to "Edit", edit_medication_path(f)
  = link_to "Delete", medication_path(f), method: :delete
  %br/
  %br/
= link_to "Home", root_path
= link_to "Add Medications", new_medication_path

app/views/medications/new.html.haml
= render 'form'

app/views/medications/show.html.haml
%h1 show
= @medication.name
= @medication.dosage
= @medication.directions
= @medication.prescriber