config/routes.rb
Rails.application.routes.draw do

  root 'hospital#index'

  resources :clinics
  resources :patients do

    member do

      patch :wait_patient
      patch :checkup_patient
      patch :xray_patient
      patch :surgery_patient
      patch :bills_patient
      patch :leave_patient
    end
  end  
  resources :medications
  resources :doctors

end

app/models/patient.rb
class Patient < ActiveRecord::Base
validates :first_name, presence: true
validates :last_name, presence: true
validates :description, presence: true

has_many :clinic_patients
has_many :clinics, through: :clinic_patients
# belongs_to :clinic
# has_many :medications, dependent: :destroy
has_many :doctors, through: :patient_doctors
has_many :patient_doctors
has_many :medications, through: :patient_medications
has_many :patient_medications

include Workflow
workflow do
	state :waiting do
		event :wait, :transitions_to => :waiting
		event :check_up, :transitions_to => :checking_up
		event :x_ray, :transitions_to => :x_raying
		event :surgery, :transitions_to => :surged
		event :leave, :transitions_to => :leaving
	end

	state :checking_up do
		event :check_up, :transitions_to => :checking_up
		event :x_ray, :transitions_to => :x_raying
		event :surgery, :transitions_to => :surged
		event :bills, :transitions_to => :billing
		event :leave, :transitions_to => :leaving
	end

	state :x_raying do
		event :x_ray, :transitions_to => :x_raying
		event :surgery, :transitions_to => :surged
		event :bills, :transitions_to => :billing
		event :leave, :transitions_to => :leaving
	end	

	state :surged do
		event :surgery, :transitions_to => :surged
		event :bills, :transitions_to => :billing
	end

	state :billing do
		event :bills, :transitions_to => :billing
		event :leave, :transitions_to => :leaving
	end	

	state :leaving do
		event :leave, :transitions_to => :leaving
	end	
end

	BLOOD_TYPE_OPTIONS = [
		"A+",
		"A-",
		"B+",
		"B-",
		"O+",
		"O-",
		"AB+",
		"AB-"
	]
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
 	before_action :set_patient, only: [
	:show,
	:edit,
	:update,
	:destroy,
	:wait_patient,
	:check_up_patient,
	:x_ray_patient,
	:surgery_patient,
	:bills_patient,
	:leave_patient
	]

	def index
		@patients = Patient.all
		@patients = if !params[:q].blank?
      Patient.where("name LIKE ?", "%#{params[:q]}%")
    else
      
      puts "Showing all Patients"
      Patient.all
    end.shuffle
	end

	def new
		# @clinic = Clinic.find params[:clinic_id]
		@patient = Patient.new
		@doctors = Doctor.all
		@medications = Medication.all
	end

	def create
	# @clinic = Clinic.find params[:clinic_id] 
		@patient = Patient.create patient_params
		@doctors = @patient.doctors
		@medications = @patient.medications
		if @patient.save
			flash[:notice] = 'Patient was added successfully.'
			redirect_to patients_path
		else 
		flash[:error] = 'Patient add unsuccessful.'	
		render :new
		end
	end

	def show
		# @clinic = Clinic.find params[:clinic_id]
		@patient = Patient.find params[:id]
		@doctors = @patient.doctors
		@medications = @patient.medications
	end	

	def edit
		# @clinic = Clinic.find params[:clinic_id] 
		@patient = Patient.find params[:id]
		@doctors = Doctor.all
		@medications = Medication.all
	end	

	def update
		# @clinic = Clinic.find params[:clinic_id]
		@patient = Patient.find params[:id]
		@patient.update_attributes patient_params
		@doctors = @patient.doctors
		@medications = @patient.medications
		redirect_to patients_path
	end 
	
	def destroy
		# @clinic = Clinic.find params[:clinic_id]
		@patient = Patient.find params[:id]
		@patient.delete
		redirect_to patients_path
	end

	def wait_patient
    # @restaurant = Restaurant.find(params[:id])  
    @patient.wait!
    redirect_to patients_path
  end

  def checkup_patient
    # @restaurant = Restaurant.find(params[:id])  
    @patient.check_up!
    redirect_to patients_path
  end

  def xray_patient
    # @restaurant = Restaurant.find(params[:id])  
    @patient.x_ray!
    redirect_to patients_path
  end

  def surgery_patient
    # @restaurant = Restaurant.find(params[:id])  
    @patient.surgery!
    redirect_to patients_path
  end

  def bill_patient
    # @restaurant = Restaurant.find(params[:id])  
    @patient.bill!
    redirect_to patients_path
  end

  def leave_patient
    # @restaurant = Restaurant.find(params[:id])  
    @patient.leave!
    redirect_to patients_path
  end

private

	def set_patient
		@patient = Patient.find(params[:id])
	end
	
	def patient_params
		params.require(:patient).permit(
			:first_name,
			:last_name,
			:date_of_birth,
			:description,
			:gender,
			:blood_type,
			clinic_ids: [],
			patient_ids: [],
			doctor_ids: [],
			medication_ids: []
			)
	end	

end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/patients/_form.html.haml
= form_for @patient do |f|
  = f.label :first_name
  = f.text_field :first_name, class: "form-control"
  %br/
  = f.label :last_name
  = f.text_field :last_name
  %br/
  = f.label :date_of_birth
  = f.date_field :date_of_birth, min: "1900-01-01", max: (Time.now)
  %br/
  = f.label :description
  = f.text_field :description
  %br/
  = f.label :gender
  = f.radio_button :gender, 'Female', :checked => true
  = label :gender, 'Female'
  = f.radio_button :gender, 'Male'
  = label :gender, 'Male'
  %br/
  = f.label :blood_type
  = f.select :blood_type, options_for_select(Patient::BLOOD_TYPE_OPTIONS, f.object.date_of_birth), include_blank: "--Choose option--"
  %br/
  - @doctors.each do |d|
    = check_box_tag 'patient[doctor_ids][]', d.id, @patient.doctors.include?(d)
    = d.name
  %br/
  - @medications.each do |m|
    = check_box_tag 'patient[medication_ids][]', m.id, @patient.medications.include?(m)
    = m.name
  = f.submit "Submit", class: "button", disabled: "disabled"

app/views/patients/edit.html.haml
= render 'form'

app/views/patients/index.html.erb
<% @patients.each do |patient| %>
	<%= patient.first_name %>
	<%= patient.last_name %>
	<%= patient.workflow_state %>
	<br>
<%= link_to "View Patient", patient_path(patient) %>
<br>
<%= link_to 'Edit', edit_patient_path(patient) %>
	<br>
<%= link_to 'Delete', patient, method: :delete, data: {confirm: 'Are you sure?'} %>
	<br>
<% end %>

<%= link_to "Add Patient", new_patient_path %>
<%= link_to "Home", root_path %>
<%= link_to "Clinics", clinics_path %>

app/views/patients/index.html.haml
%h1 Patients
= form_tag patients_path, method: :get, role: "search" do
  = text_field_tag 'q', params[:q], id: "srch-term", placeholder: "Search" 
  = submit_tag "Search"
%br
- @patients.each do |patient|
  = patient.first_name
  = patient.last_name
  = patient.workflow_state
  %br/
  = link_to "View Patient", patient_path(patient)
  %br/
  = link_to 'Edit', edit_patient_path(patient)
  %br/
  = link_to 'Delete', patient, method: :delete, data: {confirm: 'Are you sure?'}
  %br/
  - if patient.wait?
  = link_to "Doctor Check-up", checkup_patient_patient_path(patient), method: :patch
  = link_to "X-Ray", xray_patient_patient_path(patient), method: :patch
  = link_to "Surgery", surgery_patient_patient_path(patient), method: :patch
  = link_to "Leaving", leave_patient_patient_path(patient), method: :patch
  - if patient.check_up?
  = link_to "X-Ray", xray_patient_patient_path(patient), method: :patch  
  = link_to "Surgery", surgery_patient_patient_path(patient), method: :patch
  = link_to "Billing", bills_patient_patient_path(patient), method: :patch
  = link_to "Leaving", leave_patient_patient_path(patient), method: :patch
  - if patient.x_ray?
  = link_to "Surgery", surgery_patient_patient_path(patient), method: :patch
  = link_to "Billing", bills_patient_patient_path(patient), method: :patch
  = link_to "Leaving", leave_patient_patient_path(patient), method: :patch
  - if patient.surgery?
  = link_to "Billing", bills_patient_patient_path(patient), method: :patch   

= link_to "Add Patient", new_patient_path
= link_to "Home", root_path
= link_to "Clinics", clinics_path

app/views/patients/new.html.haml
%h1 New Patient
= link_to "Home", root_path
= render 'form'

app/views/patients/show.html.haml
%div Patient Profile
%br/
= "First Name:"
= @patient.first_name
%br/
= "Last Name:"
= @patient.last_name
%br/
= "DOB:"
= @patient.date_of_birth
%br/
= "Description:"
= @patient.description
%br/
= "Gender:"
= @patient.gender
%br/
= "Blood Type:"
= @patient.blood_type
%br/
%br/
%br/
%div Patient's Doctor(s)
%br/
- @doctors.each do |doctor|
  = "Dr."
  = link_to doctor.name, doctor_path(@doctor)
  %br/
%br/
%br/
%div Patient's Medications
%br/
- @medications.each do |medication|
  = medication.name
  = medication.dosage
  %br/
%br/
%br/
= link_to "Home", root_path
= link_to "Edit Patient", edit_patient_path(@patient)
= link_to "Delete Patient", patient_path(@patient), method: :delete