config/routes.rb
Rails.application.routes.draw do

  root 'hospital#index'

  resources :clinics
  resources :patients do

    member do

      patch :wait_patient
      patch :checkup_patient
      patch :xray_patient
      patch :surgery_patient
      patch :bills_patient
      patch :leave_patient
    end
  end  
  resources :medications
  resources :doctors

end

app/models/doctor.rb
class Doctor < ActiveRecord::Base
	belongs_to :patients, polymorphic: true
	belongs_to :clinics, polymorphic: true
	has_many :patients, through: :patient_doctors
	has_many :patient_doctors
	has_many :clinic_doctors
	
end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
def index
	@doctors = Doctor.all
	@doctors = if !params[:q].blank?
    Doctor.where("name LIKE ?", "%#{params[:q]}%")
  else
    
    puts "Showing all Doctors"
    Doctor.all
  end.shuffle
end	

def new
	@doctor = Doctor.new
end

def create
	@doctor = Doctor.create doctor_params
	redirect_to doctors_path
end	

def show
	@doctor = Doctor.find doctor_params[:id]
end

def edit
	@doctor = Doctor.find params[:id]
end

def update
	@doctor = Doctor.find params[:id]
	@doctor.update_attributes doctor_params
	redirect_to doctors_path
end


def destroy
	@doctor = Doctor.find params[:id]
	@doctor.delete
	redirect_to doctors_path
end

private
	def doctor_params
		params.require(:doctor).permit(
			:name,
			:office_phone_number,
			:specialty,
			doctor_ids: [],
			clinic_ids: []
			)
	end
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/views/doctors/_form.html.haml
= form_for @doctor do |f|
  = f.label :name
  = f.text_field :name
  %br/
  = f.label :office_phone_number
  = f.text_field :office_phone_number
  %br/
  = f.label :specialty
  = f.text_field :specialty
  %br/
  %br/
  = f.submit

app/views/doctors/edit.html.haml
= render 'form'

app/views/doctors/index.html.haml
Doctors
%br/

= form_tag doctors_path, method: :get, role: "search" do
  = text_field_tag 'q', params[:q], id: "srch-term", placeholder: "Search" 
  = submit_tag "Search"
%br/
- @doctors.each do |doctor|
  = "Doctor:"
  = doctor.name
  %br/
  = "Office Phone Number:"
  = doctor.office_phone_number
  %br/
  = "Specialty"
  = doctor.specialty
  %br/
  = link_to "Edit", edit_doctor_path(doctor)
  = link_to "Delete", doctor_path(doctor), method: :delete
  %br/
  %br/
= link_to "Home", root_path
= link_to "Add Doctor", new_doctor_path

app/views/doctors/new.html.haml
= render 'form'
= link_to "Home", root_path
= link_to "Doctors", doctors_path